"""Pernix — canary authoring helpers: spec validation and the shared write path.

Canaries are hand-written. The suite used to grow itself — refine turned
failed turns into candidate canaries and an allowlist proof auto-admitted
them — but in a month on the reference box auto-admission admitted nothing,
and every canary that joined was approved by a human. That path was retired
in 3.2. What stays is what the create/edit API needs:

  is_gate_command_safe — the allowlist proof, now an advisory check: the
                         API returns its verdicts as warnings.
  isolation_violation  — a spec whose task points outside the sandbox is
                         contaminated by construction, so it is refused.
  write_canary_md      — the validated write path (temp copy, real parser,
                         then move) shared by every writer.
  materialize_canary   — a structured spec rendered to CANARY.md.
"""

from __future__ import annotations

import logging
import re
import shlex
import shutil
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import yaml

logger = logging.getLogger("pernix.canary")

_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,48}$")

# Gate-command allowlist proof (advisory: the create API reports its
# verdicts as warnings). Closed-world by construction: one plain
# command (no shell metacharacters survive, so no chaining/redirection/
# substitution), binary from a fixed read-only-ish set, every path-like token
# workspace-relative. `python -c` is excluded (arbitrary code); `python -m`
# is allowed only for pytest/unittest.
_SAFE_GATE_BINARIES = frozenset(
    {"python", "python3", "pytest", "grep", "diff", "cmp", "test", "[", "cat", "head", "tail", "wc", "ls"}
)
_SAFE_PYTHON_MODULES = frozenset({"pytest", "unittest"})
_SHELL_META_RE = re.compile(r"[;&|<>`$\n\\]")


# Isolation validation at GENERATION time (L07). The runtime contamination
# scan is detection: it disqualifies a run after the fact. A canary whose
# TASK is written outside the sandbox is contaminated by construction, so it
# fails that scan every single run — `workspace-organizer-evidence-gate`,
# generated by the skill-change sweep, told the agent to organise
# `./data/workspace` and was contaminated 3 times out of 3, raising a
# high-urgency alert every night. The patterns below are exactly the ones the
# runtime scan flags, applied to the proposal before it can become a file.
_WORKSPACE_ESCAPE_RE = re.compile(r"data[/\\]workspace")


def isolation_violation(spec: dict, known_canaries: list[str] | None = None) -> str | None:
    """None when this proposal can run inside the canary sandbox, else why not.

    Checked against the prompt and any seed-file CONTENT (the keys are
    already forced workspace-relative by `_validate_spec`): both are read by
    the agent, and a task steered out of the workspace by its fixtures is as
    contaminated as one steered by its prompt.
    """
    from core.canary.contamination import (
        _ABS_PATH_RE,
        _SUITE_DIR_RE,
        SYSTEM_PREFIXES,
        _other_canary_names,
    )

    name = str(spec.get("name") or "")
    fields = {"prompt": str(spec.get("prompt") or "")}
    for rel, content in (spec.get("files") or {}).items():
        fields[f"files[{rel}]"] = str(content)

    others = _other_canary_names(name, known_canaries)
    for field, text in fields.items():
        if not text:
            continue
        # Toolchain paths are not knowledge — the runtime scan ignores them too.
        outside = sorted({p for p in _ABS_PATH_RE.findall(text) if not p.startswith(SYSTEM_PREFIXES)})
        if outside:
            return (
                f"{field} names absolute path(s) {', '.join(outside[:3])}; a canary task must be "
                "workspace-relative — it runs in a throwaway temp workspace, and anything outside "
                "it is recorded as contamination"
            )
        if _WORKSPACE_ESCAPE_RE.search(text):
            return f"{field} names data/workspace, which is the live agent workspace, not the canary sandbox"
        if _SUITE_DIR_RE.search(text):
            return f"{field} names data/canaries — a canary must not read the suite's own answer key"
        named = sorted({o for o in others if re.search(rf"(?<![\w-]){re.escape(o)}(?![\w-])", text)})
        if named:
            return f"{field} names other canaries ({', '.join(named[:3])}); every run of it would be contaminated"
    return None


def is_gate_command_safe(command: str) -> str | None:
    """Prove one gate command safe for unreviewed execution. None = safe,
    else the reason it deserves a second look."""
    cmd = (command or "").strip()
    if not cmd:
        return "empty command"
    if _SHELL_META_RE.search(cmd):
        return "shell metacharacters"
    try:
        tokens = shlex.split(cmd)
    except ValueError as e:
        return f"unparseable: {e}"
    if not tokens:
        return "empty command"
    binary = Path(tokens[0]).name
    if binary != tokens[0]:
        return "binary must be a bare name (no path)"
    if binary not in _SAFE_GATE_BINARIES:
        return f"binary {binary!r} not in allowlist"
    if binary in ("python", "python3"):
        if len(tokens) < 3 or tokens[1] != "-m" or tokens[2] not in _SAFE_PYTHON_MODULES:
            return "python allowed only as 'python -m pytest|unittest'"
    for tok in tokens[1:]:
        if tok.startswith("/") or tok.startswith("~") or ".." in Path(tok).parts:
            return f"non-workspace-relative path {tok!r}"
    return None


def _validate_spec(p: dict) -> str | None:
    name = str(p.get("name") or "").strip()
    if not _NAME_RE.match(name):
        return f"invalid name {name!r} (kebab-case, 2-49 chars)"
    if not str(p.get("prompt") or "").strip():
        return "prompt is required"
    gates = p.get("gates")
    if not isinstance(gates, list) or not gates:
        return "at least one gate is required"
    for g in gates:
        if not isinstance(g, dict) or not g.get("name") or not g.get("command"):
            return "each gate needs name and command"
    files = p.get("files") or {}
    if not isinstance(files, dict):
        return "files must be a mapping"
    for rel in files:
        if Path(rel).is_absolute() or ".." in Path(rel).parts:
            return f"files key {rel!r} must be workspace-relative"
    # Contaminated by construction — see isolation_violation.
    escape = isolation_violation(p)
    if escape:
        return f"breaks canary isolation: {escape}"
    return None


def write_canary_md(name: str, text: str, base: Path | None = None, overwrite: bool = False) -> tuple[str | None, str]:
    """Write raw CANARY.md text as data/canaries/<name>/CANARY.md, validated.

    The shared write path for every canary producer (proposal
    materialization, the CRUD API, skill verify-sync): render into a temp
    dir, round-trip through the real parser, then move/replace — a broken
    file never lands in the suite. Returns (name, "") or (None, error).
    """
    from core.canary.parser import canaries_dir, parse_canary_md

    base = base or canaries_dir()
    target_dir = base / name
    if target_dir.exists() and not overwrite:
        return None, f"canary '{name}' already exists"

    tmp_root = Path(tempfile.mkdtemp(prefix="canary-write-"))
    try:
        tmp_dir = tmp_root / name
        tmp_dir.mkdir()
        tmp_md = tmp_dir / "CANARY.md"
        tmp_md.write_text(text, encoding="utf-8")
        parsed = parse_canary_md(tmp_md)  # raises CanaryParseError on any invariant break
        if parsed.name != name:
            return None, f"frontmatter name '{parsed.name}' must match directory name '{name}'"
        base.mkdir(parents=True, exist_ok=True)
        if target_dir.exists():
            (target_dir / "CANARY.md").write_text(text, encoding="utf-8")
        else:
            shutil.move(str(tmp_dir), str(target_dir))
    except Exception as e:
        return None, f"write failed: {e}"
    finally:
        shutil.rmtree(tmp_root, ignore_errors=True)
    return name, ""


def materialize_canary(spec: dict, base: Path | None = None) -> tuple[str | None, str]:
    """Write a structured spec (POST /api/canary) as data/canaries/<name>/CANARY.md.

    Validated round-trip: render → parse_canary_md on a temp copy → move.
    Returns (name, "") on success or (None, error).
    """
    from core.canary.parser import canaries_dir

    err = _validate_spec(spec)
    if err:
        return None, err
    base = base or canaries_dir()
    name = spec["name"]
    if (base / name).exists():
        return None, f"canary '{name}' already exists"

    fm = {
        "name": name,
        "prompt": spec["prompt"],
        "gates": [
            {
                "name": str(g["name"]),
                "command": str(g["command"]),
                "watch_paths": [str(w) for w in (g.get("watch_paths") or [])],
            }
            for g in spec["gates"]
        ],
        "timeout": int(spec.get("timeout") or 600),
        "tags": [str(t) for t in (spec.get("tags") or [])],
        "last_reviewed": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
    }
    files = spec.get("files") or {}
    if files:
        fm["files"] = {str(k): str(v) for k, v in files.items()}
    body = str(spec.get("rationale") or "What this canary checks, for the humans who review it.").strip()
    text = f"---\n{yaml.safe_dump(fm, sort_keys=False, allow_unicode=True)}---\n\n{body}\n"

    got, err = write_canary_md(name, text, base=base)
    if err:
        return None, f"materialization failed: {err}"
    logger.info("Canary '%s' created from a structured spec", name)
    return got, ""
